ColorlibHQ/AdminLTE

build/less/header.less

Because of icon margin, "a" tag  must be a block element in Google Chrome

make entire breadcrumb item clickable

---

bower.json

Fixed bower.json to match the javascript file on /dist/js

Fixed .js filename in bower.json

---

dist/js/app.js

This commit will trigger the events `expanded.pushMenu` and `collapsed.pushMenu` on expanding and collapsing the right sidebar respectively as mentioned in #444.

Trigger expand/collapse events for right sidebar

---

build/less/forms.less

the form controls are preconfigured to use glyhicons but lack the support for FA icons, see #479

enable font awesome in form controls

---

build/less/select2.less

Height property can be auto or removed. I prefer to remove. because there is no height property original file

remove multiple selection height property

---

Gruntfile.js

Skip `W005` check until it will be possible to ignore it only in file `pages/examples/invoice-print.html`

Skip W005 check

---

dist/js/app.js

It's a very simple yet effective fix which prevent events on document fire more than once when using Turbolinks or similar tools.
Fixes #718, #328

Sidebar autoclose on turbolinks fixed. close #718

---

build/less/sidebar-mini.less

Do not use absolute position for .pull-right on sidebar

---

dist/js/app.js

Click event is not currently firing under angularJS implmentation. This fixes it without any breaking changes to the current functionality.

Improve tree click event handler

---

dist/css/AdminLTE.css
dist/js/app.js

Sidebar menu won't lose active class when you collapse it.
New option: **sidebarKeepMenuOpen**. If true menus inside left sidebar won't collapse.
#1080
#1002

Fixed loss of "active" class after collapsing menu

---

dist/css/AdminLTE.css
dist/js/app.js

Reverts almasaeed2010/AdminLTE#1084
An issue discovered where disabling the option does not completely revert to the old accordion implementation.

Revert "Fixed loss of "active" class after collapsing menu"

---

dist/js/app.js

I've closed #1001, because it has problems with dynamic elements. I'm pretty sure this one doesn't.

Remove sidebar click handler, before assigning one. Fix sidebar autoclose bug.

---

dist/js/app.js
documentation/build/include/adminlte-options.html
documentation/index.html

Add an option to control sidebar's tree views. I found this useful when you try to integrate the theme with React and add come custom effects/logic at the menu.

Add option to control sidemenu's tree views.

---

dist/js/app.js

This pull request fixes an issue where buttons that are part of a Bootstrap button group jump on mouseover when a Bootstrap tooltip is added to them.

Fixed jumping buttons with Bootstrap tooltip

---

dist/js/app.js

It works because it's an alias. But it might be removed without warning.
While I'm here, being able to deactivate the treeview on the sidebar would be super nice, or have it as an _opt-in_ using a CSS class like *sidebar-as-tree*.

Fixed a typo

---

pages/UI/sliders.html

- use `.bootstrapSlider()` instead of `.slider()` because `.slider()` does not work right with react.js
- add attribute:type to `.ionRangeSlider()`: related issue at [ion.rangeSlider repo](https://github.com/IonDen/ion.rangeSlider/issues/343)

sliders bug fixes

---

bower.json

The package name cannot contain uppercase letters.
https://github.com/bower/spec/blob/master/json.md#name
See #1397

fix name attribute in bower.json, fix #1397

---

pages/examples/login.html
pages/examples/register.html

Hello @almasaeed2010 
Thanks to share your incredible work and so nice admin theme.
I need to parse your html files for my PHP project but I have one problem when I met comment of this style: `increaseArea: '20%' // optional`
Because my parser remove whitespace so I got something like this: `increaseArea: '20%' // optional});});</script>`
With my changes submitted I will got something like that: `increaseArea: '20%' /* optional */});});</script>`
Regards,
Joël

Change JS comment for better parsing

---

build/js/BoxWidget.js

Previously, with a .box inside a .box, any clicking on a collapse/expand button in either .box would cause both of them to collapse/expand.  
This pull request makes sure parent and child boxes do not interfere with each other.
This should fix #1681

Fix box inside box collapsing error (#1681)

---

composer.json

Introduces support for composer installer (see [here](https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md)). With this feature PHP developers will be able to specify where they want AdminLTE installed by adding:
```
"extra": {
"installer-paths": {
"my/template/path/": ["type:template"]
}
}
```
to their composer.json

Composer installer support

---

build/less/control-sidebar.less

To see the the problem:
1. Go to https://adminlte.io/themes/AdminLTE/index2.html
2. Open the control sidebar
3. Set browser width to exactly 768px
Top padding adjustment media query was off by 1px. Window width 768px (iPad) would show the additional padding, when it should only show at < 768px.
This PR fixes that.

fix control sidebar top padding

---

.npmignore

Without them the npm package is crippled. It's hard to import `admin-lte` less files since many of them reference missing `bower_components`.
E.g. in a file `my_custom_styles.less` will line `@import "~admin-lte/build/less/AdminLTE";` fail on:
```
Module build failed:
// Import variables and mixins as a reference for separate plugins version
@import (reference) "../../bower_components/bootstrap/less/mixins";
^
Can't resolve '../../bower_components/bootstrap/less/mixins.less' in 'C:\z\my_project\node_modules\admin-lte\build\less'
in C:\z\my_project\node_modules\admin-lte\build\less\bootstrap-social.less (line 11, column 0)
```

Update npmignore: don't ignore bower_components

---

build/js/Layout.js

When .main-header is generated dynamically, height becomes undefined on onload.
NaN is assigned to min-height of .content-wrapper by undefined calculation.
I fixed the problem.

Fixed an issue where height becomes NaN when there is no main-header

---

build/less/skins/skin-black-light.less
build/less/skins/skin-black.less

#1926 - [ISSUE 1925 - black layout, but font logo on the top is blue.](https://github.com/almasaeed2010/AdminLTE/issues/1925)
I'm having the blue color problem when using ngx-admin-lte
the black skin looks like this:
black and black-light
```
> .logo {
.logo-variant(#fff; #333);
border-right: 1px solid @gray-lte;
@media (max-width: @screen-header-collapse) {
.logo-variant(#222; #fff);
border-right: none;
}
}
```
and all others like this (without the '>' ):
```
//Logo
.logo {
.logo-variant(darken(@<color>, 5%));
}
```

fix(skins): ISSUE 1925 - black layout, but font logo on the top is blue.

---

pages/forms/advanced.html

Fix #1962 missing icons (up and down) due to Bootstrap 4 dropped the Glyphicons icon font, using icons from Font Awesome instead (bootstrap-timepicker plugin's configuration).

Fix #1962 Problems with Timepicker in AdminLTE v3 (missing icons)

---

build/js/Layout.js

Fix Layout content height to consider footer-height when setting min-height

[BUGFIX] #1944 Layout min-height consider footer-height [v3]

---

documentation/index.html

pi-hole's dashboard has been using AdminLTE for a long time, yet was not in this list. So I am adding it.

Add pi-hole's dashboard to implementations

---

documentation/build/include/implementations.html

This PR adds a link to https://adminlte.io/docs/2.4/implementations for a Symfony 4 compatible AdminLTE bundle.
The currently linked version has many flaws / does not work correct with the latest Symfony framework (version 4).
I started working on that bundle, as I desperately needed a solution one for my own project. Thought I share it with the community, as more and more people are upgrading to the latest framework version and need a solution for their theme.

added Symfony 4 compatible AdminLTE bundle

---

build/scss/_login_and_register.scss

- remove `box-shadow` of input `:focus`
- add border on `input-group-append` according to the status
- fix boostrap issue [#25110](https://github.com/twbs/bootstrap/issues/25110) temporarily by adding border-radius manually

fix($login-and-register): input border breaks when focus and with validation class

---

build/js/BoxWidget.js

On v2.4.9, BoxWidget collapsing is broken by a typo.
This patch fixes it.

Fix typo which breaks BoxWidget collapsing.

---

dist/js/adminlte.js

Now the collapse and expand event are triggered after the event loop, Fixes #2019

Treeview expand

---

pages/forms/general.html

It causes label text to wrap to the next line
**BEFORE**
**AFTER**

Fix wrong label column number

---

.gitignore
package.json

According to the documentation module "cleancss".
To generate a source map, use --source-map switch, e.g.:
cleancss --source-map --output styles.min.css styles.css
Name of the output file is required, so a map file, named by adding .map suffix to output file name, can be created (styles.min.css.map in this case).
If you do not make changes, then when executing the "css-minify" script, a warning is issued:
+ npm : WARNING: Empty selector '' at dist/css/adminlte.css.map:1:0. Ignoring. line:1 sign:1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (WARNING: Empty ...:1:0. Ignoring.:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
+ WARNING: Invalid property name '"version"' at dist/css/adminlte.css.map:1:1. Ignoring.

Package.json -> scripts. Module "cleancss"

---

build/config/rollup.config.js
package.json

1. Moving settings files to one place.
2. Warning correction.
>  Babel plugin: Using "external-helpers" plugin with rollup-plugin-babel is deprecated, as it now. automatically deduplicates your Babel helpers.

Change "js-compile" script. Moving settings files to one place.

---

.travis.yml
README.md

For a sample build, see https://travis-ci.org/phansys/AdminLTE/builds/559747706.
In order to get this working, you must enable the project at Travis CI: https://travis-ci.org/ColorlibHQ/AdminLTE.
`README.md` was also updated to include the build status badge.
By now, the build executes the install steps using NPM and Bower, which allows us to detect any problem caused by these processes.
There are no tests running yet since the project itself has no tests. When they are added, the `script` configuration at `.travis.yml` must be updated.

Build on Travis CI

---

build/npm/Publish.js
package.json

My environment: win7-x64.
If deleted the folder 'plugins' and calling: ``` npm run-script plugins ``` I get an error
Module 'ncp' cannot recursively create new folders for copying files from another directory into them.
Maybe this problem only windows system, but if using the module 'fs-extra' - this problem disappears.
Module 'ncp' is the oldest and has not been updated for a long time compared to 'fs-extra'.

Changing module to work with the file system. Remove 'ncp'.

---

build/scss/_table.scss

At v3-beta1, `.table-valign-middle` class worked correctly, but now it doesn't. I think this class is set at the `table` tag, so this fix is needed.

Fix for table-valign-middle doesn't work

---

build/scss/_cards.scss

Card color mixins were included after main card CSS in _cards.scss causing cards with the .card-outline-tabs to have part of their CSS overridden causing a doubled border. Simply changing the order of the CSS rules fixed the issue.
Tab card with .card-outline-tabs on MASTER:
Tab card with .card-outline-tabs after fix:

Fixed double border on cards with nav tabs

---

pages/forms/editors.html

- Summernote is the editor being used in the html file but the documentation and license info is referenced to a different github repo. It's kinda misleading

Update Doc and License info of editor

---

.github/workflows/node-install.yml

* remove the non-LTS Node.js 13
* specify `CI: true` environment variable
* switch to `npm ci` which checks for package-lock.json and it's intended for CI
I'm marking it as draft to check any failures and fix them. Also, ideally the other deps PRs should land first, so I'll wait to rebase this.
EDIT: the failures should be fixed after the deps PRs are merged, so let's wait a bit :) Also, CI should be faster after the deps PRs and this lands.

Update CI config

---

package.json

I have to say, that was a nice bug 😁
So, basically, the split dist CSS files were not using proper CSS prefixes all this time.

Fix prefix script to run for all CSS files

---

docs/_config.yml
docs/_includes/head.html
docs/_includes/navbar.html
docs/components/direct-chat.md
docs/components/main-header.md

* duplicate `title` tag; jekyll-seo-tag adds the title by default
* escape `<`
* fix duplicate IDs
* fix typo `Documentaion`
* add missing `alt` attributes in direct-chat.md

docs: fix HTML errors

---

docs/Gemfile

@REJack do you build the docs locally only? If so, maybe you don't need the `github-pages` gem which installs 85(!) gems.
But I'll leave that for you to tackle later. This patch removes redundant gems; `github-pages` gem includes those.
EDIT: also is generally good practice to include Gemfile.lock in the repo, like you do with package-lock.json. And perhaps specify a version for the `github-pages` gem; now it installs the latest all the time.

Cleanup Gemfile and add wdm on Windows

---

package-lock.json
package.json

Fixes #2714.
@REJack opened the PR but needs testing from your side. No hurry of course :)
This leaves 3 npm audit errors coming from one devDependency on master.

Update jQuery to v3.5.1.

---

package.json

Rename `install` script to `postinstall`

---

.bundlewatch.config.json
.github/workflows/ci.yml
package-lock.json
package.json

IMO it's useful, but you might not want to do it :)
That being said, the limits I chose are mostly strict. You can tweak them as needed. Also, this checks with gzip compression, but you can tweak it as needed. https://bundlewatch.io/#/reference/configuration
TODO:
Note that this won't run from forks PRs due to the secrets not being available. But the npm script will run which should mark the build as failed if the limits are surpassed.

Add bundlewatch

---

.bundlewatch.config.json
build/js/CardRefresh.js
build/js/CardWidget.js
build/js/ControlSidebar.js
build/js/DirectChat.js
build/js/Dropdown.js
build/js/ExpandableTable.js
build/js/Layout.js
build/js/PushMenu.js
build/js/SiteSearch.js
build/js/Toasts.js
build/js/TodoList.js
build/js/Treeview.js

Should result in better compression (aprox. **-10%** from the compressed adminlte.min.js) and should be easier to see unused/undefined variables on lint stage.
Draft because
1. I found an error; lint fails now (also, not sure about the `ready` usage there)
2. I think I found another spot with unneeded code (added TODO comment also)
3. Need to finish with the other open PRs
@REJack please check the TODO and let me know how to proceed in each case.
Fixes #2704

Switch to String constants

---

.browserslistrc
docs/browser-support.md

* use the defaults
* drop Edge < 15
* drop Android since newer Android uses Android WebView which is Chromium-based
This is under discussion of course, but supporting so old browsers (which are dead BTW) makes no sense. We keep them upstream because we have a stricter policy, but maybe this doesn't apply to your case.
**master**:
```
C:\Users\xmr\Desktop\AdminLTE-or>npx autoprefixer --info
Browsers:
Chrome for Android: 81
Firefox for Android: 68
And_qq: 10.4
UC for Android: 12.12
Android: 81, 4.4.3-4.4.4, 4.4
Baidu: 7.12
Chrome: 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45
Edge: 83, 81, 80, 79, 18, 17, 16, 15, 14, 13, 12
Firefox: 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, …
```

Update browserslist config

---

build/scss/mixins/_backgrounds.scss

Fixes #2786. This is just a temporary fix to ignore the warnings and add reminders to remove the dependencies.

fix: ignore warnings for bg-gradient-variant deprecation and add TODO for removing dependencies

---

build/js/TodoList.js

This was addressed in issue #2997 
This PR fixes on the issue by properly attaching the event listener (from $(SELECTOR_DATA_TOGGLE) to this._element) and fix on the options passed on in the JQuery API. This will then allow the element to have an event listener when the element does not have the data-widget set.
However, a new bug comes from this fix when both Data API and JQuery API is set which will cause the event listener be triggered twice. So users will have to only use either one of the Data or JQuery API and not both at the same time.

Small fix for TodoList plugin

---

.gitpod.yml
README.md

Hi.
I work for Gitpod. This PR adds gitpod config to the repo to make contributions easier for newcomers i.e with a single click it will launch a workspace and automatically:
- clone the `AdminLTE` repo.
- install the dependencies.
- run `yarn dev` to start the server.
This can be helpful for beginners i.e they can start coding instantly without setting anything up.
You can give it a try on my fork of the repo via the following link:
https://gitpod.io/#https://github.com/nisarhassan12/AdminLTE
This is how it looks:

make contributions easier via automating the dev setup.

---

build/js/Layout.js

layout size bug fixed

---

build/js/ExpandableTable.js
build/scss/_table.scss
pages/tables/simple.html

1. Add selector '.expandable-body' when selecting the expandable body,
2. Add class "expandable-table-caret" to the caret icon,
3. Update the example in pages\tables\simple.html.

Improve expandable table

---

build/scss/_main-sidebar.scss

This commits adds support for SVG Font Awesome icon within the main sidebar. Font Awesome translate i tags to svg tags, resulting in the angle icon not rotating in the sidebar.
Fixes #3532

Support SVG Font Awesome icon in main sidebar

---

.bundlewatch.config.json
build/js/CardRefresh.js

Currently, if a server error occurs while loading contents in the card-refresh plugin, the overlay just stays and the spinner turns forever. With this change, the overlay will be hidden if an error occurs and there is an error handler function in the settings

add errorhandling to cardrefresh plugin

---

build/scss/_sidebar-mini.scss

Fix to show the **sidebar search** when focus/hover on the sidebar mini (and not using `.sidebar-no-expand` class). Also, the sidebar search results will be hidden when **sidebar mini** is in the collapsed mode.
These bug are related to issue #3597 
I suggest to give it a review since this is my first contribution here and I'm not familiarized with the source code structure.

Show sidebar search when hover/focus in the sidebar mini

---

build/js/Fullscreen.js

Fix full screen icon change when exit the full screen mode using the **ESC** key. Related issue: #3638 
These changes implement detection of full screen events in order to toggle the icon of the full screen button. This way we can ensure the icon is always the right one. You can check next video with testing on local environment:
https://user-images.githubusercontent.com/63609705/116474614-1bf73280-a84f-11eb-8333-d051635f6906.mp4
**IMPORTANT:** Note this won't impact when entering/exiting the full screen mode using the **F11** key. There is no current workaround for this one, you can read more about this situation on next link:
https://stackoverflow.com/questions/43392583/fullscreen-api-not-working-if-triggered-with-f11

Fix icon change when enter/exit full screen mode

---

build/scss/_buttons.scss
pages/UI/buttons.html

This PR adds new rows with `light` and `dark` buttons variants examples to the `pages/UI/buttons.html` page and make some fixes on their style.
Style problem in dark-mode for the `.btn-dark` class:
Style problem in dark-mode for the `.btn-outline-dark` class:
Style problem in default mode for the `.btn-outline-light` class:
The new styles for default mode. Note how `.btn-outline-light` is now visible for the user.
The new styles for dark mode. Note how `.btn-dark` and `.btn-outline-dark` are now visible for the user.

Add new light and dark buttons variants to buttons page

---

build/scss/_info-box.scss

Currently, if the tittle or description of an `info-box` widget is too long, there is an overflow issue, as shown on next image:
This PR fix that issue adding the `overflow:hidden` property to the `info-box-content` class to solve that issue, as shown on next image:
However, note that ellipsis are used when text overflows, mainly because inner elements have the `text-overflow: ellipsis;`  and `white-space: nowrap;` properties, as shown next:
```css
.progress-description,
.info-box-text {
display: block;
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
}
```
We can also remove those properties, to get a long description or title spawn over multiple lines, but I'm not sure if that one is the desired effect. Check next image for an example:

Fix overflow style on info-box-content class.

---

build/scss/_buttons.scss
build/scss/mixins/_backgrounds.scss

Currently, when hover on some buttons (`btn-default` or buttons with `bg-gradient-*` classes) the hover effect is enabled. Those effects are not enabled for the other buttons (`btn-primary`, `btn-info`, etc.). Check next videos for an example:
**Hover effect on `.btn-default`**:
https://user-images.githubusercontent.com/63609705/118375333-75719800-b597-11eb-9324-0e9410fba0b1.mp4
**Hover effect on `.btn.bg-gradient-*`**:
https://user-images.githubusercontent.com/63609705/118375330-71de1100-b597-11eb-86c2-057664bf279e.mp4
This PR removes the hover effect from the mentioned buttons to match the behaviour present for most of the buttons. Check next videos for the result of applying this PR:
**NO hover effect on `.btn-default`**:
https://user-images.githubusercontent.com/63609705/118375332-730f …

Fix disabled style for some buttons.

---

build/js/Treeview.js

The recently pushed PR #3647 tried to solve an icon issue on child menus when closing a parent treeview menu. See issue #3643 for details. However, this introduces a new issue, now child menus are not collapsed when closing a parent treeview menu, see next video:
https://user-images.githubusercontent.com/63609705/121935083-6dd01b00-cd1e-11eb-9972-c01aa1a08f39.mp4
This PR solves the icon issue in a proper way, not introducing the mentioned new issue. Check next the video showing the behaviour when using this PR:
https://user-images.githubusercontent.com/63609705/121935503-e040fb00-cd1e-11eb-8401-006398e4018f.mp4

Fix childs behaviour when closing a parent treeview menu

---

build/js/IFrame.js
build/js/Layout.js
docs/javascript/iframe.md

In relation to #3822
- Revert some changes that where introduced on the fix https://github.com/ColorlibHQ/AdminLTE/commit/4a2a28f799146867c6b0717936cb14de082e9792 because they do not solve the intended issue #3822 and introduced some other problems related to the height.
In relation to #3872
- Add a fix to solve height calculation of a default tab on the **IFrame** plugin.
- Change documentation of the **IFrame** plugin, to remove hardcoded height for the default tabs. Height can't be hardcoded because height depends on the client screen.

Fix height problem on default tabs for the IFrame plugin

---

.dockerignore
Dockerfile
docker-compose.yml
package.json

In order to create an isolated environment to work on this code, I create some docker-related files (Dockerfile, .dockerignore and docker-compose) to easily set up a contributor environment just running `docker-compose up`
It's based on node 14 LTS version, publishing the 3000 and 3001 ports to the host machine.
We can consider a middle point between just raw install over the machine the repo or run on Gitpod. The main differences are:
- against raw installation:
- Isolated environment with a standard node LTS engine
- Just one step to run the development environment
- against Gitpod:
- Freedom to choose the IDE/editor of your preference

Use docker to run the development enviroment

---

README.md

Somewhere along the way this task changed names and was not updated in the docs.

Fix gulp readme typo

---

build/scss/_cards.scss
build/scss/mixins/_cards.scss

Fix card-outline-tabs in dark mode, which had a line above the header and also in the active tab, and when hovering the mouse in the active tab, the color also changed
after the changes

Fix card-outline-tabs in dark mode and hover

---

build/js/SidebarSearch.js

Encoded URI:
http%3A%2F%2F127.0.0.1%
3A8001%2F
Decoded URI:
http://127.0.0.1:8001/

Fix Bug for encoding URI

---

build/scss/mixins/_backgrounds.scss

This solves the error when building in Laravel mix. On other hand, this error was already mentioned in #4255. 
See the error:
```bash
SassError: Top-level selectors may not contain the parent selector "&".
╷ 
7 │   &.bg-#{$name} {
│   ^^^^^^^^^^^^^^
╵
```
How it was solved:
See documentation: https://sass-lang.com/documentation/style-rules/parent-selector#in-sassscript where says:
`If the & expression is used outside any style rules, it returns null. Since null is [falsey](https://sass-lang.com/documentation/at-rules/control/if#truthiness-and-falsiness), this means you can easily use it to determine whether a mixin is being called in a style rule or not`
I hope that it helps other people.

Add verification use of & outside of style rules

---

package.json

Issue : #4394
Rename package **flag-icon-css** to **flag-icons**

Fix: deprecated packages flag-icon-css

---

build/js/IFrame.js

When embedding whole admin-lte page into a iframe, mini sidebar will display without content.
JS error code: `Uncaught TypeError: Cannot read properties of null (reading 'autoIframeMode')`
html iframe code:
```
<html>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<head>
<style type="text/css">
html, body {
border: 0px;
margin: 0px;
padding: 0px;
}
#admin-lte{
height: 480px;
width: 640px;
}
</style>
</head>
<body>
<iframe id="admin-lte" src="index.html" frameborder="0" scrolling="no"></iframe>
</body>
</html>
```

Fix a mini sidebar bug when embedding admin-lte into iframe

---

src/html/components/_scripts.astro
src/ts/push-menu.ts

Added checks to some scripting to check if a sidebar exists before trying to load some code that affects the sidebar and throws console errors because there was no sidebar on the page.

Issue 5011- Add checks for if sidebar exists to stop errors on pages with no sidebar

---

src/html/components/dashboard/_topbar.astro
src/ts/adminlte.ts
src/ts/fullscreen.ts

I added a full screen button to the top menu as it was available in the BS4 version.
I saw that there is a PR for this already but it seems to be outdated.
(This is my first PR here so hopefully I did it right).
Best regards,
George

Fullscreen button

---

src/html/components/_scripts.astro
src/html/components/dashboard/_sidenav.astro
src/html/pages/UI/general.astro
src/html/pages/components/general.astro
src/html/pages/forms/general.astro
src/scss/_toasts.scss
src/scss/_variables.scss
src/scss/adminlte.scss
src/scss/parts/_extra-components.scss

The current code includes a Forms => General Elements page that shows basic Bootstrap 5 form elements.
In this PR I added a Components => General Components page showing basic Bootstrap 5 components.
(I also used this branch to fix some minor things in the form elements page.)

Bs5 Components

---

src/html/components/_head.astro
src/scss/_bootstrap-variables.scss
src/scss/adminlte.scss

This was a feature request #5296
I also ran into cases where I had to switch to local Google fonts due to European GDPR laws (loading fonts from Google transfers the user's IP address to Google without his consent).
The currently used font Source Sans Pro has been updated and is now named "Source Sans 3". I downloaded the woff2 files for weights 300, 400 and 700 (normal and italic) in cyrillic, cyrillic-ext, greek, greek-ext, latin, latin-ext and vietnamese versions (as the remote CSS from Google fonts currently provides).
I left the reference to the remote Google fonts in `_head.astro` in case someone wants to use those. However, in that case the user also needs to remove the references to the local font files and re-compile adminlte.css.

Local Google Fonts

---

src/ts/treeview.ts

Add changes on `src/ts/treeview.ts` file to parse next data attributes in order to configure the **treeview plugin** from `HTML` markup.
- `data-accordion`
- `data-animation-speed` 
The `data-accordion` was already used in the source code, see file `src/html/components/dashboard/_sidenav.astro` at line `35`, but it was never parsed by the plugin:
```html
<ul
class="nav sidebar-menu flex-column"
data-lte-toggle="treeview"
role="menu"
data-accordion="false"
>
```
As a sidenote, what the status of this package @REJack @danny007in , are you guys still working on it? I'm curious because I'm working on an integration of **AdminLTE v4** for **Laravel** and I need to know what to expect on the future around this package...

Add logic to parse data attributes on treeview plugin
