documentation/index.html
https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/AdminLTE.css#L44
=> Update documentation for .layout-boxed

pages/calendar.html
Hi,
im going to work on app base on AdminLTE and fullcalendar, next week. Today just check calendar page and it doesnt work for me,... Cause by absence protocols to external sites.
=> Calendar: add missing protocols for external lib

build/less/dropdown.less
Fix Animation issue in the LESS file :)
=> Fix Animation on Safari

index2.html
This will eliminate unnecessary downloads.
=> Removed redundant link and script elements

dist/js/pages/dashboard.js, pages/forms/advanced.html
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).
=> Fixed Moment.js deprecation warning

dist/css/AdminLTE.css
=> Typo in AdminLTE.css

pages/tables/data.html
https://www.datatables.net/manual/api
https://datatables.net/upgrade/1.10-convert
The changes with this pull-request are to encourage using the new Datatables 1.10 API.
=> Datatables, examples, switching to the new 1.10 API.

dist/js/app.js
=> Allow collapsible form in box

plugins/chartjs/Chart.js
=> Update ChartJS to 1.0.2

build/less/navs.less
https://github.com/almasaeed2010/AdminLTE/issues/429
=> navs add different color

Gruntfile.js, package.json
Added Bootstrap linter requested in #638
=> Added Bootstrap linter

pages/UI/buttons.html, pages/charts/chartjs.html, pages/charts/flot.html, pages/charts/inline.html, pages/charts/morris.html, pages/examples/blank.html, pages/examples/invoice.html, pages/examples/lockscreen.html, pages/examples/profile.html, pages/forms/advanced.html, pages/forms/editors.html, pages/forms/general.html, pages/layout/boxed.html, pages/layout/collapsed-sidebar.html, pages/layout/fixed.html, pages/mailbox/compose.html, pages/mailbox/mailbox.html, pages/mailbox/read-mail.html, pages/tables/simple.html, pages/widgets.html
Fixed all warnings W007 listed in #652
=> Fixed Bootlint warning W007

pages/UI/general.html
Fixed error E033 listed in #652
=> Fixed Bootlint error E033

pages/charts/inline.html
Fixed error E029 listed in #652
=> Fixed Bootlint error E029

documentation/index.html
Fixed typo in documentation/index.html
=> Fixed typo: way -> ways

documentation/build/include/implementations.html
Add a link to the new gem that uses less and it's more maintainable
=> Add new rails gem supporting AdminLTE sources

dist/js/app.js
Fix bug with treeview menu when sidebar is collapsed and you clicked to menu which already visible.
=> Fix animation bug with collapsed sidebar and treeview menu.

index2.html
Duplicate attribute type="button"
=> Duplicate attribute type button

README.md, package.json
Added the 'main' property to the package.json file for easy discovery/inclusion in a project using NPM.
=> added main property to package.json

changelog
=> updated changelog with already released versions

pages/widgets.html
hi.
I changed widget page source
a href="index2.html" class="logo"
to
a href="../index2.html" class="logo"
because it didn't linked to index2.html file in root dir.
thank you for your great project.
=> logo link changed in wigdet page.

package.json
Update npm version to v2.3.11. Thanks!
=> Bump npm version to v2.3.11.

README.md
This PR simply fixes the `README` markdown syntax. Now we can see the screenshot.
=> Fix Screenshot Mardown

plugins/jvectormap/jquery-jvectormap-1.2.2.css
Fixed comment in jquery-jvectormap-1.2.2.css
=> Fix Comment

documentation/build/include/implementations.html, documentation/index.html
This is a version of AdminLTE that makes it easy to use Vue.js. It has been catching good traction. Would be honored if it were included in the implementation section of the documentation.
=> Added CoPilot to example implementations. 

bower.json, index.html, pages/calendar.html
=> managed jquery-ui by bower

pages/charts/chartjs.html
=> corrected error in the chart path in the charts pages

index2.html
This PR will fix missing Chart.js on Index2.html. This missing file causes by typo which is written Chart.js where it should be chart.js
=> Fix Missing Chart.js File

build/js/Layout.js, dist/js/adminlte.js
=> #1947   fixed content-wrapper height

build/js/Widget.js
feel free to do it your way
#1910
=> fix(js): AdminLTE 3 collapse button

build/scss/_navs.scss
feel free to do it your way
https://github.com/almasaeed2010/AdminLTE/issues/1893
=> same text-color as background for nav-item:hover dropdown

.gitattributes, composer.json
Added export-ignore files by .gitattributes,  as there are too many files which we do not need when import the package.
=> add gitattributes

build/js/BoxWidget.js
Add Collapsing, Expanding and Removing Events
=> Add Collapsing, Expanding and Removing Events

composer.json
=> Bootstarap 3 > 4

build/config/rollup.config.js, package.json
Upgrading to new versions of these modules did not change the compiled output javascript files. But we updating modules to the lastest stability version.
=>  Updating devDependencies for "js" script.

docs/Gemfile, docs/_includes/head.html, docs/_includes/sidebar.html
- removed duplicate `<!DOCTYPE html>` and `<html lang="en">`
- added missing source line and github-pages gem in Gemfile
- fixed brand-link in docs
=> fixed docs bugs for generation 

README.md
This file (changelog.md) no longer appears active; removing reference from README.md
=> Remove changelog.md link

docs/index.md
I found it in official docs: https://adminlte.io/docs/3.0/
=> typo fix on 'yarn add'

index.html
=> fixed resizing bugs with chartjs in index.html

pages/layout/top-nav.html
=> Fix broken link

pages/gallery.html
Correction of `filtr-item`'s `data-category`, and add Category 4 (COLORED, BLACK).
=> Correct and Improve the FilterizR sample of gallery page.

pages/calendar.html
allDay event of FullCalendar need `allDay : true`.
=> Correct all day event of FullCalendar.

pages/examples/project_add.html
=> Title Changed from Project Edit to Project Add

docs/components/cards.md, docs/javascript/card-widget.md
Fixed typo in cards.md and card-widget.md
=> Fixed typo in docs

pages/UI/navbar.html
Fixed duplicated ids on NavBar Example page
=> NavBar Example had duplicated ids

build/scss/_miscellaneous.scss, pages/UI/navbar.html
Don't know if i did it right, double check plz... 
There's a way to avoid the use of a overlay-wrapper? i'm not good in css....
=> Overlay for tab-panels

docs/implementations.md
I created 3 boilerplate projects with Admin LTE 3.04
=> add implementations of Angular, React and Vue

pages/tables/data.html
=> add container-fluid

index2.html
Might be worth running [vnu-jar](https://www.npmjs.com/package/vnu-jar) on all HTML files to make sure everything is valid :)
=> Fix invalid `href` value

package-lock.json, package.json, plugins/daterangepicker/daterangepicker.js, plugins/daterangepicker/package.js, plugins/daterangepicker/website/index.html
You should not include the daterangepicker/website files @REJack :)
Feel free to push to my branch or fix it later.
Changelog: https://github.com/dangrossman/daterangepicker/compare/v3.0.5...v3.1
=> Update daterangepicker to v3.1.0

package-lock.json, package.json
=> Remove unused devDependencies

package-lock.json
Should save a couple hundred packages.
@REJack you should try updating rollup-plugin-babel. Feel free to look upstream for the patch in case it helps. :)
=> Regenerate package-lock.json to flatten deps.

.github/workflows/node-install.yml
Non-whitespace diff: https://github.com/ColorlibHQ/AdminLTE/pull/2721/files?w=1
EDIT:
I didn't add caching because it's super slow on Windows: https://github.com/actions/cache/issues/336
Might want to revisit later.
=> Simplify CI

README.md, docs/faq.md, docs/index.md
Might conflict later, just ping me to rebase.
=> Fix GitHub case.

package.json
Might conflict, if so ping me to rebase :)
=> Specify `--format breakWith=lf` for cleancss

.lgtm.yml
The languages are auto-detected AFAICT.
@REJack please disable PR comments if you haven't already done it :)
Looking into the rest.
=> Configure LGTM

docs/dependencies.md, pages/examples/invoice.html
=> Add `rel=noopener` for external links.

index3.html, pages/UI/modals.html, pages/examples/e-commerce.html, pages/examples/invoice-print.html, pages/forms/general.html, pages/forms/validation.html
The rest after I set up the validator and we are done with the open PRs :)
=> A few HTML validation fixes

build/scss/_buttons.scss, build/scss/_cards.scss, build/scss/_carousel.scss, build/scss/_forms.scss, build/scss/_main-header.scss, build/scss/_main-sidebar.scss, build/scss/_miscellaneous.scss, build/scss/_small-box.scss, build/scss/_timeline.scss, build/scss/plugins/_fullcalendar.scss, pages/mailbox/mailbox.html
=> Remove glyphicon leftovers.

.gitignore
=> Fix .gitignore comments

build/config/rollup.config.js, build/js/CardRefresh.js, build/js/CardWidget.js, build/js/ControlSidebar.js, build/js/DirectChat.js, build/js/Dropdown.js, build/js/Layout.js, build/js/PushMenu.js, build/js/SiteSearch.js, build/js/Toasts.js, build/js/TodoList.js, build/js/Treeview.js
Non-whitespace diff: https://github.com/ColorlibHQ/AdminLTE/pull/2774/files?w=1
=> Remove unneeded IIFEs

build/js/AdminLTE.js
This is nitpicking :)
Assuming none of the JS plugins depends on each other, this should be OK. If any plugin depends on another, let me know.
=> Sort imports/exports alphabetically

build/js/CardWidget.js, build/js/ControlSidebar.js, build/js/Layout.js, build/js/PushMenu.js, build/js/Toasts.js, build/js/TodoList.js
@REJack please test this carefully, in case I overdid it. I tested this, but the more the better.
=> Cache selectors when possible.

build/npm/Plugins.js, plugins/jsgrid/demos/db.js
It's used in pages/tables/jsgrid.html.
Fixes #2808
=> Add back jsgrid/demos/db.js

docs/javascript/layout.md
I'll check later if there are more cases.
=> layout.md: Escape `\`

build/js/ExpandableTable.js, build/npm/vnu-jar.js, docs/404.html, docs/components/control-sidebar.md, pages/gallery.html, pages/tables/simple.html
Refs https://github.com/ColorlibHQ/AdminLTE/pull/2528#issuecomment-639997251
Feel free to push to this branch to fix the table warnings. The rest I guess we could ignore them, although they are still valid (you probably don't want to use a `section` there). The problem is we can't ignore only a specific line, we need to disable the error/warning globally.
So, ideally, all warnings should be fixed so that we don't have have to ignore any extra stuff. :)
=> vnu: enable `Werror`

build/scss/_alerts.scss, build/scss/_buttons.scss, build/scss/_cards.scss, build/scss/_control-sidebar.scss, build/scss/_direct-chat.scss, build/scss/_dropdown.scss, build/scss/_info-box.scss, build/scss/_layout.scss, build/scss/_main-sidebar.scss, build/scss/_miscellaneous.scss, build/scss/_products.scss, build/scss/_small-box.scss, build/scss/_timeline.scss, build/scss/mixins/_accent.scss, build/scss/mixins/_cards.scss, build/scss/mixins/_custom-forms.scss, build/scss/mixins/_direct-chat.scss, build/scss/mixins/_miscellaneous.scss, build/scss/mixins/_navbar.scss, build/scss/mixins/_toasts.scss, build/scss/pages/_invoice.scss, build/scss/pages/_lockscreen.scss, build/scss/pages/_login_and_register.scss, build/scss/pages/_mailbox.scss
Notes:
1. I didn't change the scss/plugins files because some plugins do use the shorthand. **It should be tackled too, though, by using `background-image` or `background-color` where appropriate.**
@REJack feel free to push to this branch to fix the plugin instances :)
Fixes #2726
=> Be explicit with the background color property

.eslintrc.json, build/js/CardWidget.js, build/js/ControlSidebar.js, build/js/Dropdown.js, build/js/Layout.js, build/js/Treeview.js
Draft because the other PRs need to be sorted.
=> Use template literals

build/js/ControlSidebar.js
It's not a lot more readable, but at least the variables are set once. This could be simplified later further.
=> ControlSidebar.js: minor simplification

build/scss/mixins/_backgrounds.scss
Reverts ColorlibHQ/AdminLTE#2852
=> Revert "fix: ignore warnings for bg-gradient-variant deprecation and add TODO for removing dependencies"

.github/dependabot.yml
* switch to weekly updates
* increase versions
* add bundler deps too
=> Tweak dependabot config

pages/UI/buttons.html
=> add btn-app color variations demo

.github/workflows/ci.yml, .github/workflows/docs.yml
Enable cache on Windows and fix cache directory to work on all OS'es
=> Tweak CI cache

build/scss/_pagination.scss, build/scss/parts/_core.scss, pages/UI/general.html
=> add pagination month

build/js/ExpandableTable.js, build/scss/_table.scss, pages/tables/simple.html
Preview Default ![grafik](https://user-images.githubusercontent.com/1554582/87957654-d8e28480-cab0-11ea-8594-26ba0afaa4ad.png)
Closes #2360
=> enhance ExpandableTable for table tree

build/scss/_brand.scss, docs/components/main-sidebar.md
Preview: 
_There is no demo with this enhancement placed, only styles and docs added_
Closes #2597
=> enhance brand-link with pushmenu inside brand

build/scss/_buttons.scss, build/scss/_cards.scss, build/scss/_carousel.scss, build/scss/_forms.scss, build/scss/_main-header.scss, build/scss/_main-sidebar.scss, build/scss/_miscellaneous.scss, build/scss/_small-box.scss, build/scss/_timeline.scss, build/scss/plugins/_fullcalendar.scss
=> add font awesome light & duotone icons support

.bundlewatch.config.json, build/scss/_buttons.scss, build/scss/_cards.scss, build/scss/_carousel.scss, build/scss/_forms.scss, build/scss/_main-header.scss, build/scss/_main-sidebar.scss, build/scss/_miscellaneous.scss, build/scss/_small-box.scss, build/scss/_timeline.scss, build/scss/plugins/_fullcalendar.scss, pages/UI/general.html
=> add support for fontawesome svg icons

pages/charts/inline.html
=> add sparkline demo in inline charts

docs/_config.yml, docs/additional-styles.md, docs/javascript/direct-chat.md, docs/javascript/expandable-tables.md
=> docs updates/changes

pages/charts/flot.html, pages/gallery.html
=> remove unnecessary jquery-ui

build/js/PushMenu.js
=> remove sidebar-is-opening on expand

build/js/ControlSidebar.js
=> fix control-sidebar height with layout-fixed

.bundlewatch.config.json, build/js/SidebarSearch.js, build/scss/_main-sidebar.scss
=> sidebar search enhancements

index.html, index2.html, index3.html, pages/UI/modals.html, pages/UI/ribbons.html, pages/UI/sliders.html, pages/calendar.html, pages/charts/chartjs.html, pages/charts/flot.html, pages/charts/inline.html, pages/examples/forgot-password.html, pages/examples/invoice-print.html, pages/examples/login.html, pages/examples/recover-password.html, pages/forms/advanced.html, pages/forms/editors.html, pages/forms/general.html, pages/forms/validation.html, pages/gallery.html, pages/layout/top-nav-sidebar.html, pages/layout/top-nav.html, pages/mailbox/compose.html, pages/mailbox/mailbox.html, pages/tables/data.html, pages/tables/jsgrid.html
=> move demo code after 3rd-party scripts

build/js/Dropdown.js, build/js/Treeview.js, build/scss/_cards.scss, docs/javascript/control-sidebar.md
Closes #2919, closes #2698, closes #2940 & closes #2953
=> some plugin fixes

docs/implementations.md
Video tutorial link add into implementation section. so, any one setup adminLTE theme into laravel in just few minutes.
=> docs: Video tutorial link add into docs

pages/widgets.html
=> fix direct-chat classes in pages/widgets

build/scss/_forms.scss
=> fix input-group-text font-size with body.text-sm

build/scss/_pagination.scss
Removed box shadow from page-link class
=> Removed box shadow from page-link class

build/scss/_close.scss, build/scss/_forms.scss, build/scss/parts/_components.scss
Remove outline from close button
=> Smileyzn close button patch 1

build/scss/_main-sidebar.scss, build/scss/mixins/_sidebar.scss
=> CSS sidebar classes to handle long text #2816 in scss

build/scss/_layout.scss
=> footer height bug fix

build/js/Layout.js, build/scss/_layout.scss, build/scss/_main-sidebar.scss
Removed Unnecessary Code
And
Sidebar improved (Can work smoothly without overlayScrollbars plugin)
=> sidebar upgradeed

pages/charts/inline.html, pages/examples/contacts.html, pages/examples/language-menu.html, pages/examples/legacy-user-menu.html, pages/examples/pace.html, pages/kanban.html, pages/mailbox/compose.html, pages/mailbox/mailbox.html, pages/mailbox/read-mail.html
Resolved this html [conflict](https://github.com/danny007in/AdminLTE/commit/3afd696833b17d7dc7bed14120b7906e2260b961)
=> html bug fix

build/scss/_layout.scss
=> Fixed: Top Nav Page has sidebar with blank in v3.1.0-rc

docs/_config.yml, docs/contributing.md, docs/dependencies.md, docs/index.md, docs/layout.md
Added Contributing Guide in Docs.
Added CDN link of jsDelivr.
Improved some info.
=> Docs improved for Adminlte 3.1

README.md
- Change link on readme to latest releases page.
=> Fix link to latest release

build/js/IFrame.js
Done #3233
and
lgtm warning fixed
=> iFrame bug fixed

build/js/Layout.js, build/scss/_layout.scss
Fixed https://github.com/ColorlibHQ/AdminLTE/pull/3157#issuecomment-742501904
Removed Unwanted Codes that causes performance slow down
=> Content Height Fixed and Removed Unused Code

docs/components/main-header.md, docs/layout.md
- Added Dark mode Info 
- Fixed Top nav demo img size
=> Docs improve

build/scss/_variables.scss
=> Removed Unused Sass Variables

docs/layout.md
Fixes https://github.com/ColorlibHQ/AdminLTE/issues/3286
=> Update docs - layout page (remove css class)

build/config/postcss.config.js, build/scss/_layout.scss, build/scss/_main-sidebar.scss, build/scss/_sidebar-mini.scss, build/scss/mixins/_miscellaneous.scss, build/scss/mixins/_sidebar.scss, package-lock.json, package.json
Fixed of https://github.com/ColorlibHQ/AdminLTE/issues/3304
=> Sidebar scroll fixed (#3304)

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/lint.yml
* remove `CI: true` since it's set by the runner
* update to `actions/setup-node@v2`
* switch to `ruby/setup-ruby` Action
* specify `FORCE_COLOR: 2`
* lowercase `runner.os`
* update to Ruby 2.7
* update to Node.js 14.x
* fix npm cache mismatches due to wrong variable
=> Update CI config

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
I excluded the plugins folders because otherwise it takes too long to scan. That being said, I suggest that you scan everything in a temp branch (for example https://github.com/ColorlibHQ/AdminLTE/security/code-scanning?page=1&query=ref%3Arefs%2Fheads%2Fcodeql-test), report any issues upstream and/or consider using other plugins if there are replacements.
Obviously you should wait a bit for the upstream developers to have a look at these issues because some might be false positives :)
PS. I already contacted the OverlayScrollbars dev so that's one less project to contact
=> Add CodeQL

package-lock.json, package.json
Fixed https://github.com/ColorlibHQ/AdminLTE/issues/3212
=> Nodemon parallel fix

.stylelintignore, CODE_OF_CONDUCT.md, LICENSE, build/npm/vnu-jar.js, docs/dependencies.md, docs/javascript/iframe.md, docs/javascript/layout.md, package.json, pages/UI/general.html, pages/examples/lockscreen.html, pages/search/enhanced-results.html, pages/search/simple-results.html
- added Code of conduct
- updated docs
- .stylintignore update
- year bump in html/js
- improved package.json
=> Docs, html, js minor changes

build/scss/_main-sidebar.scss, build/scss/_navs.scss
Perfect Fix: https://github.com/ColorlibHQ/AdminLTE/issues/3449
=> Fix: sidebar light in dark-mode

build/js/SidebarSearch.js
Fixed https://github.com/ColorlibHQ/AdminLTE/issues/3556
=> Fix: sidebar search url issue

docs/layout.md
It was saying that the layout consists of four major parts. But there were three items listed.
=> Updated layout documentation.

.github/CONTRIBUTING.md, index2.html
1. Fixed Browser card in index2.html that wasn't reflecting dark mode
2. Fixed some typos in CONTRIBUTING.md
=> Fixed Browser Card dark mode in index2.html and CONTRIBUTING.md

docs/javascript/treeview.md
https://github.com/ColorlibHQ/AdminLTE/issues/3674
=> fix treeview sample code

pages/examples/project-add.html
=> Fixed Typo

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, package-lock.json
Almost like https://github.com/twbs/bootstrap/commit/41330696b9fd9f29db089fccdbe433677b92bb4a
=> :boom: Switch to Node.js 16 and npm 8.

build/js/ControlSidebar.js
=> Fixed toggling multiple control sidebar

build/scss/_bootstrap-variables.scss, build/scss/_cards.scss, build/scss/_main-header.scss, build/scss/_main-sidebar.scss, build/scss/_variables.scss, build/scss/plugins/_select2.scss
=> Fix Using / for division is deprecated

src/partials/dashboard/_sidenav.html, src/scss/_nav-sidebar.scss
This PR is to do the changes proposed in issue #4110
=> Change side menu chevrons pointing side

src/utils/index.js
Improved path conversion to allow any number of subpaths
=> Improved path conversion to allow any number of subpaths

package-lock.json, package.json
Fixes https://github.com/ColorlibHQ/AdminLTE/issues/5340
=> astro check bug fix

src/html/components/dashboard/_sidenav.astro, src/html/pages/UI/icons.astro
=> Added Icons in UI
